### ISSUE TITLE
React.createClass is deprecated

### ISSUE THREAD

**Issue by saadist** [coma/svg-reactify#10]
React.createClass is deprecated and will be removed in version 16. Use plain JavaScript classes instead. If you're not yet ready to migrate, create-react-class is available on npm as a drop-in replacement.

**Comment by luontola** [comment]
React.createClass has been removed in React 16, so this issue is now a showstopper for React 16 upgrades.

**Comment by devxpy** [comment]
+1

**Comment by coma** [comment]
https://github.com/coma/svg-reactify/pull/13
