### ISSUE TITLE
dependencies not up to date

### ISSUE THREAD

**Issue by pawlufelice** [coma/svg-reactify#5]
Please, could you update the dependencies?

Thanks,
Paul

**Comment by coma** [comment]
Hello everyone! (@pawlufelice, @mudetroit, @andersaloof, @brandly)

I've finally released [a new version](https://github.com/coma/svg-reactify/tree/v2.x) under an alpha tag hoping to have some feedback from you before tagging it as stable.

BTW, if [this](https://github.com/babel/babel/pull/3376#issuecomment-189408436) comes true, we can think of having a SVG2React transform directly on Babel allowing its use for both, Browserify and Webpack, pretty neat.

Cheers.
