### ISSUE TITLE
Allow React ^15.0.0 in peerDependencies

### ISSUE THREAD

**Issue by m90** [coma/svg-reactify#7]
While working fine when monkey patching (i.e. installing a local clone where I just changed the range in package.json) it's not possible to install `svg-reactify` alongside React 15 as the peerDependencies in package.json specify `^0.14`. Are there any reasons for not specifying sth like `^0.14.0 || ^15.0.0`?

**Comment by coma** [comment]
done! https://github.com/coma/svg-reactify/releases/tag/2.0.0

**Comment by m90** [comment]
Nice!
